number1 = float(input('Zadehte číslo: '))
number2 = float(input('Zadehte číslo: '))
number3 = float(input('Zadehte číslo: '))
number4 = float(input('Zadehte číslo: '))
number5 = float(input('Zadehte číslo: '))
